services:
  db:
    image: postgres:15
    container_name: usability_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: usability_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_data: